---

- name: Ensure facts can be stored locally
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install system packages
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  retries: 3
  with_items:
    - libsemanage-python
    - policycoreutils-python
  tags:
    - server

