---

- name: Ensure facts can be stored locally
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install system packages
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  retries: 3
  with_items:
    - libsemanage-python
    - policycoreutils-python
    - curl
    - wget
    - unzip
    - bzip2
    - net-tools
  tags:
    - server

- name: Install Extra Packages
  become: yes
  when: server.packages is defined and ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: '{{ server.packages }}'
  tags:
    - server

- name: ensure firewalld is running
  become: yes
  when: buildserver_ip_address is defined and ansible_os_family == 'RedHat'
  service: name=firewalld enabled=yes state=started
  tags:
    - firewall
    - server

- name: Grant SSH access for buildserver
  become: yes
  when: buildserver_ip_address is defined and ansible_os_family == 'RedHat'
  firewalld: rich_rule='rule family="ipv4" source address="{{ buildserver_ip_address }}" port port="22" protocol="tcp" accept' permanent=true state=enabled immediate=yes
  notify: restart firewalld
  tags:
    - firewall
    - server

